name: Nuget publish

on: 
  release:
    types:
    - published

jobs:
  pack:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12
    steps:
    - uses: actions/checkout@v2
    - name: get version
      run: |
        PATTERN="refs/tags/v"
        echo $GITHUB_REF | grep "${PATTERN}"
        VERSION=$(echo $GITHUB_REF | sed "s|${PATTERN}||")
        if [ -z "${VERSION}" ]; then
          echo VERSION variable is empty. Current ref: $GITHUB_REF
          exit 1
        fi
        echo VERSION is ${VERSION}
        echo "::set-env name=VERSION::${VERSION}"
    - name: pack redlock
      run: dotnet pack --configuration=Release -o "../target/packages" /p:Version=${{ env.VERSION }} ./RedlockDotNet
      working-directory: src
    - name: pack redlock redis
      run: dotnet pack --configuration=Release -o "../target/packages" /p:Version=${{ env.VERSION }} ./RedlockDotNet.Redis
      working-directory: src
    - name: Upload release asset for RedlockDotNet
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/packages/RedlockDotNet.${{ env.VERSION }}.nupkg
        asset_name: RedlockDotNet.${{ env.VERSION }}.nupkg
        asset_content_type: application/zip
    - name: Upload release asset for RedlockDotNet.Redis
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/packages/RedlockDotNet.Redis.${{ env.VERSION }}.nupkg
        asset_name: RedlockDotNet.Redis.${{ env.VERSION }}.nupkg
        asset_content_type: application/zip
    - name: Publish packages on nuget
      working-directory: ./target/packages
      env:
        NUGET_PUSH_KEY: ${{ secrets.NUGET_PUSH_KEY }}
      run: |
        echo "Publishing ${{ env.VERSION }} version"
        dotnet nuget push RedlockDotNet.${{ env.VERSION }}.nupkg --api-key "${NUGET_PUSH_KEY}" --source "https://api.nuget.org/v3/index.json"
        dotnet nuget push RedlockDotNet.Redis.${{ env.VERSION }}.nupkg --api-key "${NUGET_PUSH_KEY}" --source "https://api.nuget.org/v3/index.json"
